
@startuml
skinparam classAttributeIconSize 0
class Admin{
    -role: String
    ~Admin()
}

class Customer{
    -address: String
    -postalCode: String
    -city: String
    ~Customer()
    +getAddress()
}

abstract User {
    #username: String
    #password: String
    #fullname: String
    #email: String
    #phoneNumber: String
    ~User()
    +getUsername()
    +getPassword()
}




class HashCollectionList<0> {
    -dataHash: Hashmap<String, O>
    +HashCollectionList()
    +exist(String userhash)
    +addUser(String userhash, O user)
    +deleteUser(String userhash)
    +getUser(String userhash)
    +updateUser(String userhash, O updatedUser)

}

User <|-- Admin
User <|-- Customer
HashCollectionList *-- Admin
HashCollectionList *-- Customer
@enduml